name: Build Dotnet Windows AMI

on:
  push:
    branches:
      - dotnet-windows-final

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run packer init
        id: init
        run: packer init ./image.pkr.hcl

      - name: Run packer validate
        id: validate
        run: packer validate ./image.pkr.hcl

      - name: Build AMI
        run: packer build ./image.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
