name: Build Dotnet Windows AMI

on:
  push:
    branches:
      - dotnet-windows-base

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Insert winrm password
        id: winrmpass
        run: |
          sed '3s/.*/net user Administrator $SECRET_PASSWORD/' winrm.ps1 > winrm_temp.ps1
          mv winrm_temp.ps1 winrm.ps1
        env:
          SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run packer init
        id: init
        run: packer init .

      - name: Run packer validate
        id: validate
        run: packer validate -var "admin_password=$SECRET_PASSWORD" .
        env:
          SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}

      - name: Build AMI
        run: packer build -on-error=cleanup -debug -var "admin_password=$SECRET_PASSWORD" .
        env:
          SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
